
version: '3'
services:
  node_server:
    image: nipunshaji190/node_server:test
    build: ./server
    # image: nipunshaji190/node_server.slim:latest
    # image: nipunshaji190/node_server:test-slim
    environment:
      - DB_URL=mongodb+srv://root:toor@cluster0.51apq.mongodb.net/tododb?retryWrites=true&w=majority
    ports:
      - '9000:9000'
  vue_client:
    image: nipunshaji190/vue_client:test
    build: ./client
    # image: nipunshaji190/vue_client.slim:latest
    # image: nipunshaji190/vue_client:test-slim
    depends_on:
      - node_server
    ports:
      - '3000:3000'
  reverse-proxy:
    image: nipunshaji190/reverse_proxy:latest
    build: ./reverse_proxy
    container_name: reverse_proxy
    depends_on:
      - vue_client
      - node_server
    ports:
      - 80:80
