version: '3'
services:
  node_server:
    image: njames92/todo-mevn_node_server:latest
    build: ./server
    environment:
      - DB_URL=mongodb+srv://root:toor@cluster0.51apq.mongodb.net/tododb?retryWrites=true&w=majority
    ports:
      - '9000:9000'
  vue_client:
    image: njames92/todo-mevn_vue_client:latest   
    build: ./client
    depends_on:
      - node_server
    ports:
      - '3000:3000'
  reverse-proxy:
    image: njames92/reverse_proxy:latest
    build: ./reverse_proxy
    container_name: reverse_proxy
    depends_on:
      - vue_client
      - node_server
    ports:
      - 80:80