version: '3'
services:
  # Proxy to internal services
  reverse-proxy:
    image: nginx:1.17.10
    container_name: reverse_proxy
    depends_on:
      - vue_client
      - node_server
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  vue_client:
    build: ./client
    command: bash -c "npm install && npm run dev"
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - '3000:3000'
    environment:
      HOST: 0.0.0.0

  node_server:
    build: ./server
    command: bash -c "npm install && npm run serve"
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - DB_URL=mongodb://mongo:27017/tododb
    ports:
      - '9000:9000'
    depends_on:
      - mongo

  mongo:
    image: mongo
    volumes:
      - ./tmp/data:/data/db
    ports:
      - '27017:27017'
