version: '3'
services:
  # Proxy to internal services
  reverse-proxy:
    image: nginx:1.17.10
    container_name: reverse_proxy
    depends_on:
      - vue_client
      - node_server
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  vue_client:
    image: nipunshaji190/vue_client:test-ubuntu
    build: ./client
    # command: bash -c "npm install && npm run dev"
    environment:
      HOST: 0.0.0.0
    ports:
      - '3000:3000'

  node_server:
    image: nipunshaji190/node_server:test-ubuntu
    build: ./server
    # command: bash -c "npm install && npm run serve"
    environment:
      - DB_URL=mongodb://mongo:27017/tododb
    ports:
      - '9000:9000'
    depends_on:
      - mongo

  mongo:
    image: mongo
    volumes:
      - ./tmp/data:/data/db
    ports:
      - '27017:27017'
