version: 2.1

orbs:
  aws-ecs: circleci/aws-ecs@1.3.0

workflows:
  slim_and_push:
    jobs:
      - aws-ecs/deploy-service-update:
          aws-access-key-id: $AWS_ACCESS_KEY_ID
          aws-secret-access-key: $AWS_SECRET_ACCESS_KEY
          aws-region: $AWS_REGION 
          family: $PRE_FAMILY
          service-name: $PRE_SERVICE_NAME
          cluster-name: $PRE_CLUSTER_NAME
          container-image-name-updates: 'container=$PRE_CONTAINER_NAME,tag=$TAG'  
          force-new-deployment: true